[package]
name = "raytracing"
version = "0.1.0"
authors = ["Ward <ward.gauderis@student.uantwerpen.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
image = "0.23.14"

[profile.dev]
opt-level = 3
